Check Uri for Knowledge Base Creation
AKSW/OntoWiki pull request #400
Opened 2016-10-04 22:35 UTC by shinobu

This fix checks the URI for knowledge base creation for http:// 

This Pull Request does fix  #399

2016-10-14 12:03 UTC, white-gecko requested changes
The wording of the error message should be improved. Further it would be good to implement the fix in Erfurt and catch the according exception here.
Please also check at which level OntoWiki is already catching such Exceptions.

2016-10-14 12:03 UTC, white-gecko commented on application/controllers/ModelController.php
> +                    new OntoWiki_Message('The given String is no legal URI (http://...)', OntoWiki_Message::ERROR)
The hint "http://…" connotes, that the algorithm already identified the missing protocol part, while there might be other cases for the value not being a valid URI or IRI.

2016-10-14 12:03 UTC, white-gecko commented on application/controllers/ModelController.php
> +                    new OntoWiki_Message('The given String is no legal URI (http://...)', OntoWiki_Message::ERROR)
"String" is a very technical term in this case, better use "value"

2016-10-14 12:03 UTC, white-gecko commented on application/controllers/ModelController.php
> +                    new OntoWiki_Message('The given String is no legal URI (http://...)', OntoWiki_Message::ERROR)
Since we are aiming for IRI support, it is better to write IRI or URI (resp. other way round)

2016-10-14 12:03 UTC, white-gecko commented on application/controllers/ModelController.php
> +                    new OntoWiki_Message('The given String is no legal URI (http://...)', OntoWiki_Message::ERROR)
Also check if the check supports IRIs

2016-10-19 21:11 UTC, shinobu commented
done in https://github.com/AKSW/Erfurt/pull/129 --- is the error message ok?

2016-11-02 20:38 UTC, shinobu commented
now uses error codes to check if the exception gets catched or not

2017-05-02 09:51 UTC, white-gecko commented
Do URNs (urn:…) and https:// URI still work?

2017-05-02 15:36 UTC, shinobu commented
are urn:'s really valid RDF/Modelnames?

2017-05-03 08:29 UTC, white-gecko commented
What about ftp://… and tel:… I think there are more valid kinds of URIs and afaik all of them are allowed for models.

2017-05-12 19:26 UTC, shinobu commented
We are now using the PHP filter `FILTER_VALIDATE_URL`, We might need to add a test (the ModelController has no tests at all right now) to check if the filter works for all PHP versions though.

2017-05-12 21:48 UTC, white-gecko commented
Could you add the test?

2017-06-20 09:27 UTC, white-gecko requested changes
Finally please rebase and squash the commits.

2017-06-20 09:27 UTC, white-gecko commented on application/tests/integration/controller/ModelControllerTest.php
> +            ['\\äüö', false]
Please add some more failing examples

2017-06-20 09:27 UTC, white-gecko commented on application/tests/integration/controller/ModelControllerTest.php
> +
Please also check the coding standard with code sniffer

2017-06-28 09:37 UTC, white-gecko requested changes

2017-06-28 09:37 UTC, white-gecko commented on application/controllers/ModelController.php
> +                    )
Why do you touch this twice?

2017-06-28 09:37 UTC, white-gecko commented on application/controllers/ModelController.php
>   * @license   http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
This can go to the first commit.

2017-07-08 16:26 UTC, shinobu commented
Done @white-gecko 
This should be mergeable now

2017-07-10 09:15 UTC, white-gecko approved these changes

2017-07-10 09:15 UTC, merged