add link to new documentation
AKSW/OntoWiki pull request #415
Opened 2016-12-06 11:56 UTC by shinobu

This pull request adds a link to the new documentation

2016-12-06 14:30 UTC, white-gecko commented
The README ist still important, so the phrase "This documentation …" is not good. It should just be a prominent link to the documentation. I've already disabled the wiki here on GitHub,

2016-12-06 14:32 UTC, shinobu commented
oh sorry, i didn't know it was already deactivated, gonna change that in a sec

2016-12-06 16:17 UTC, white-gecko commented
I think the link should be more prominent. Maybe you add an extra section before the Introduction.

2016-12-06 17:03 UTC, shinobu commented
you can check it again @white-gecko

2017-04-18 09:54 UTC, white-gecko commented
The documentation link should go to the top of the README file.
And please squash the commits.

2017-04-23 16:19 UTC, shinobu commented
I added the link at the top, put the ##Documentation at the bottom (the notice about how they can propose changes is in my point of view important)

2017-04-24 14:19 UTC, white-gecko commented
Please check it again! Build-Status is now linked to docs.ontowiki.net. You could also update the build status using the travis icons.

2017-04-24 18:55 UTC, shinobu commented
I have literary no idea how that even could have happen.
Fixed it, added the Travis build status (still kept the owdev one for now), changed the look so that it resembles Erfurt

should be ok now @white-gecko

2017-04-25 09:21 UTC, pfrischmuth requested changes

2017-04-25 09:21 UTC, pfrischmuth commented on README.md
> +[Documentation](https://github.com/AKSW/docs.ontowiki.net)
Link seems to be wrong

2017-04-25 09:21 UTC, pfrischmuth commented on README.md
> +| owdev Jenkins  | [![owdev Build Status](http://owdev.ontowiki.net/job/OntoWiki/badge/icon)](http://owdev.ontowiki.net/job/OntoWiki/)  |
Please remove it

2017-04-25 11:27 UTC, white-gecko commented
I'd like to care for this ;-)

[![Latest Stable Version](https://poser.pugx.org/aksw/ontowiki/v/stable)](https://packagist.org/packages/aksw/ontowiki) [![Total Downloads](https://poser.pugx.org/aksw/ontowiki/downloads)](https://packagist.org/packages/aksw/ontowiki) [![Latest Unstable Version](https://poser.pugx.org/aksw/ontowiki/v/unstable)](https://packagist.org/packages/aksw/ontowiki) [![License](https://poser.pugx.org/aksw/ontowiki/license)](https://packagist.org/packages/aksw/ontowiki) [![composer.lock](https://poser.pugx.org/aksw/ontowiki/composerlock)](https://packagist.org/packages/aksw/ontowiki)

![api_doc](https://cloud.githubusercontent.com/assets/1018168/25383098/c9d5c712-29ba-11e7-9532-ac70099ae929.png) ![user_doc](https://cloud.githubusercontent.com/assets/1018168/25383110/d494da80-29ba-11e7-81c2-08c26da6218f.png)

2017-04-25 11:55 UTC, white-gecko commented
The actual images can be seen in my comment

2017-04-28 13:12 UTC, pfrischmuth approved these changes
LGTM

2017-04-28 13:12 UTC, merged

2017-04-28 15:05 UTC, white-gecko commented
@pfrischmuth works, it was the rawgit cache delaying the delivery of the SVG files.