Clean php and phtml files from outcommented Code
AKSW/OntoWiki pull request #419
Opened 2017-01-06 11:24 UTC by shinobu

This pull request removes most/all outcommented Code in the php and phtml files in OntoWiki (including extensions).

2017-01-06 13:20 UTC, white-gecko requested changes
Looks good, just two changes.

2017-01-06 13:20 UTC, white-gecko commented on application/views/templates/application/openid.phtml
> -//]]>
These should stay

2017-01-06 13:20 UTC, white-gecko commented on application/views/templates/application/webid.phtml
> -//]]>
same here

2017-01-06 16:42 UTC, shinobu commented
done @white-gecko

2017-01-06 16:52 UTC, shinobu commented
Tests:
Unit:
OK (86 tests, 154 assertions)
Virtuoso;
Tests: 27, Assertions: 138, Errors: 1. (same as develop branch)
MySQL:
OK (27 tests, 139 assertions)

2017-04-18 09:51 UTC, white-gecko requested changes

2017-04-18 09:51 UTC, white-gecko commented on extensions/semanticsitemap/templates/semanticsitemap/sitemap.phtml
> -<!-- Semantic Sitemap generated by <?php echo $this->appname ?> <?php echo $this->version ?> -->
This should stay as well

2017-04-18 09:51 UTC, white-gecko commented on extensions/navigation/templates/navigation/explore.phtml
> +<!-- <li> -->
Why is this still here?

2017-04-18 09:51 UTC, white-gecko commented on extensions/navigation/templates/navigation/explore.phtml
> +<!-- <li> -->
Also the following h2

2017-04-23 15:13 UTC, shinobu commented
corrected those things, rebased, squashed

should be OK now

2017-04-25 11:10 UTC, white-gecko approved these changes
LGTM ;-)

2017-04-25 11:10 UTC, merged