Enable Travis tests for all testsuites
AKSW/OntoWiki pull request #420
Opened 2017-02-09 20:18 UTC by shinobu

This pull request enables travis for all testsuites

2017-02-10 13:28 UTC, white-gecko requested changes

2017-02-10 13:28 UTC, white-gecko commented on .travis.yml
> +  - '7.1'
Please also make the same changes here as for Erfurt

2017-02-10 16:39 UTC, shinobu commented
done, added indention fix as well @white-gecko

2017-02-17 12:42 UTC, white-gecko approved these changes

2017-02-17 12:43 UTC, merged